print("Welcome to HolbieTapsi a great app to order taxis in Barranquilla city")
print("What would you like to do?")
print("1 - To dispatch a taxi")
print("2 - To Add a taxi to the station")
orden = input("Enter your option ")
